# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhXQSl4EUS740Ft7d6zAZ246EZNOiG69
"""

rain = True

if rain:
  print("Take sn umbrella")