# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igpL22H9oQDd4OiW-1DnToAFwNkigcBr
"""

temp = 40
rain = True

if temp>30:
  print("Stay inside")
else:
  print("Go outside")