# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxcR4ZQ0kZauxu2-utZ6n6dE7it4YyGJ
"""

marks= int(input("Enter your marks"))
if marks >= 90:
  print("A")
elif marks >=75:
  print("B")
elif marks >=50:
  print("C")
else:
  print("Fail")