# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dljdiS8OodICbbTXeexlEJyYIEChprP7
"""

temp = 30

if temp>35:
  print("It's very hot")
elif temp>25:
  print("It's warm")
else:
  print("It's cold")