# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOsmN85R3jHL0IW1_V3iMSvs1dlESpBA
"""

age= int(input("Enter your age: "))
if age>=18:
  print("Eligible for vote")
else:
  print("Not eligible for vote")