# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCvTln2GwYVmm9RjfdzN5ACqW1p07kS-
"""

rain = False

if rain:
  print ("Take an umbrella")
else:
  print("No need for an umbrella")