# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxtY1cR6VL4LhzFiY5F-E_VtvHhEI9Ms
"""

username = input("Enter your username: ")
password = input("Enter your password: ")

if username == "Hie" :
  if password == "Prachi":
    print("Congratulations, it's correct")
else:
        print("Oopsie, it's wrong")