# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzVtzVefZsLHtgSgAOGGL0tthgr5Oqqx
"""

temp=30
rain=False

if temp>25 and not rain:
  print("Go for a walk")