# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jw4h8W7Cbr8AIohHuGwp3NAMJkWDvmd
"""

num= int(input("Enter the number: "))
if (num % 4 == 0 and num % 100 != 0) or (num % 400 == 0) :
  print("It's a leap year")
else:
  print("It's not a leap year")