# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrp_daB18eThMuQh0LnzmxNJf9SYEdPZ
"""

num= int(input("Enter your number"))
if num>0:
  print("Positive")
elif num<0:
  print("Negative")
else:
  print("Zero")